---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

name: fedora-silverblue-cosmic-42paris
description: Atomic image with Cosmic DE and common utilities, based on Fedora Silverblue

base-image: ghcr.io/ublue-os/silverblue-main
image-version: 44

modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* into your image's root folder /

  - type: systemd
    system:
      enabled:
        - nix.mount

  - type: dnf
    #repos:
    #  copr:
    #    - atim/starship
    install:
      packages:
        - tmux
        - screen # For switch/router serial port

        - '@cosmic-desktop-environment'

        # H264 on Firefox
        #- gstreamer1-plugins-good-extras
        #- gstreamer1-plugins-ugly

        # Yubikey & U2F
        - yubikey-manager
        - pam-u2f
        - pamu2fcfg

        - krb5-workstation # Kerberos (kinit etc)

        # Moar packages
        #- rpmfusion-free-release
        #- rpmfusion-nonfree-release

        # Network
        - wireshark # The flatpak version can't do capture
        - wireguard-tools
        #- tcpdump
        #- nmap
    remove:
      packages:
        # Remove firefox, in favor of the flatpak
        - firefox
        - firefox-langpacks

  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        install: # system flatpaks we want all users to have and not remove
          - org.mozilla.firefox
          - org.remmina.Remmina    # VNC client
          - com.bitwarden.desktop  # Password manager
          - dev.edfloreshz.CosmicTweaks # GNOME Tweaks but for Cosmic DE
          - com.getpostman.Postman # REST client
          - com.discordapp.Discord
          - com.slack.Slack
          - com.github.tchx84.Flatseal # Modify permissions of Flatpak apps
          - org.gnome.seahorse.Application # GNOME "Passwords and Keys"
          - com.yubico.yubioath
          - ca.desrt.dconf-editor
      - scope: user # Also add Flathub user repo, but no user packages

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
